//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ComponentInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ComponentInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ComponentInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ComponentInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_ComponentInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint m_iParent {
    set {
      Engine2PINVOKE.ComponentInfo_m_iParent_set(swigCPtr, value);
    } 
    get {
      uint ret = Engine2PINVOKE.ComponentInfo_m_iParent_get(swigCPtr);
      return ret;
    } 
  }

  public string m_strName {
    set {
      Engine2PINVOKE.ComponentInfo_m_strName_set(swigCPtr, value);
    } 
    get {
      string ret = Engine2PINVOKE.ComponentInfo_m_strName_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64 m_iMemoryUsage {
    set {
      Engine2PINVOKE.ComponentInfo_m_iMemoryUsage_set(swigCPtr, SWIGTYPE_p_uint64.getCPtr(value));
      if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64 ret = new SWIGTYPE_p_uint64(Engine2PINVOKE.ComponentInfo_m_iMemoryUsage_get(swigCPtr), true);
      if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_uint64 m_iCount {
    set {
      Engine2PINVOKE.ComponentInfo_m_iCount_set(swigCPtr, SWIGTYPE_p_uint64.getCPtr(value));
      if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_uint64 ret = new SWIGTYPE_p_uint64(Engine2PINVOKE.ComponentInfo_m_iCount_get(swigCPtr), true);
      if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public ComponentInfo() : this(Engine2PINVOKE.new_ComponentInfo(), true) {
  }

}
