//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ERenderer {
  eRN_D3D9,
  eRN_D3D10,
  eRN_OGL,
  eRN_OGL_ES,
  eRN_FLASH
}
