//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IDecalManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IDecalManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IDecalManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IDecalManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_IDecalManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual uint SpawnDecal(EngineDecalInfo arg0) {
    uint ret = Engine2PINVOKE.IDecalManager_SpawnDecal(swigCPtr, EngineDecalInfo.getCPtr(arg0));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool MoveDecal(uint decalID, EngineDecalInfo arg1) {
    bool ret = Engine2PINVOKE.IDecalManager_MoveDecal(swigCPtr, decalID, EngineDecalInfo.getCPtr(arg1));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual SWIGTYPE_p_IMaterial GetDecalMaterial(uint decalID) {
    global::System.IntPtr cPtr = Engine2PINVOKE.IDecalManager_GetDecalMaterial(swigCPtr, decalID);
    SWIGTYPE_p_IMaterial ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_IMaterial(cPtr, false);
    return ret;
  }

  public virtual IMeshInfo GetDecalMesh(uint decalID) {
    global::System.IntPtr cPtr = Engine2PINVOKE.IDecalManager_GetDecalMesh(swigCPtr, decalID);
    IMeshInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new IMeshInfo(cPtr, false);
    return ret;
  }

  public virtual bool RemoveDecal(uint id) {
    bool ret = Engine2PINVOKE.IDecalManager_RemoveDecal(swigCPtr, id);
    return ret;
  }

  public virtual void SetTransparency(uint id, float fTransparency) {
    Engine2PINVOKE.IDecalManager_SetTransparency(swigCPtr, id, fTransparency);
  }

  public virtual float GetTransparency(uint id) {
    float ret = Engine2PINVOKE.IDecalManager_GetTransparency(swigCPtr, id);
    return ret;
  }

}
