//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IDeviceDependendentInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IDeviceDependendentInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IDeviceDependendentInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IDeviceDependendentInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_IDeviceDependendentInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual EDeviceType GetDeviceType() {
    EDeviceType ret = (EDeviceType)Engine2PINVOKE.IDeviceDependendentInfo_GetDeviceType(swigCPtr);
    return ret;
  }

  public virtual int GetSupportedTextureFormatsCount() {
    int ret = Engine2PINVOKE.IDeviceDependendentInfo_GetSupportedTextureFormatsCount(swigCPtr);
    return ret;
  }

  public virtual string GetSupportedTextureFormat(int num) {
    string ret = Engine2PINVOKE.IDeviceDependendentInfo_GetSupportedTextureFormat(swigCPtr, num);
    return ret;
  }

}
