//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ILogManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ILogManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ILogManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ILogManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_ILogManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void RegisterListener(ILogListener arg0) {
    Engine2PINVOKE.ILogManager_RegisterListener(swigCPtr, ILogListener.getCPtr(arg0));
  }

  public virtual void AddToLog(SWIGTYPE_p_uint32 attr, string format) {
    Engine2PINVOKE.ILogManager_AddToLog(swigCPtr, SWIGTYPE_p_uint32.getCPtr(attr), format);
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetLastErrorLogging(bool arg0) {
    Engine2PINVOKE.ILogManager_SetLastErrorLogging(swigCPtr, arg0);
  }

  public virtual SWIGTYPE_p_uint32 GetLastErrorCount() {
    SWIGTYPE_p_uint32 ret = new SWIGTYPE_p_uint32(Engine2PINVOKE.ILogManager_GetLastErrorCount(swigCPtr), true);
    return ret;
  }

  public virtual string GetLastError(SWIGTYPE_p_uint32 arg0) {
    string ret = Engine2PINVOKE.ILogManager_GetLastError(swigCPtr, SWIGTYPE_p_uint32.getCPtr(arg0));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void ClearLastErrorList() {
    Engine2PINVOKE.ILogManager_ClearLastErrorList(swigCPtr);
  }

  public virtual void SetLogCallback(SWIGTYPE_p_p_f_p_q_const__char__void arg0) {
    Engine2PINVOKE.ILogManager_SetLogCallback(swigCPtr, SWIGTYPE_p_p_f_p_q_const__char__void.getCPtr(arg0));
  }

  public virtual ERendererError GetLastRenderError() {
    ERendererError ret = (ERendererError)Engine2PINVOKE.ILogManager_GetLastRenderError(swigCPtr);
    return ret;
  }

  public virtual void SetLastRenderError(ERendererError eLastError) {
    Engine2PINVOKE.ILogManager_SetLastRenderError(swigCPtr, (int)eLastError);
  }

}
