//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IMeshFactory : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IMeshFactory(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IMeshFactory obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IMeshFactory() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_IMeshFactory(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public void DeleteMeshInfo(IMeshInfo mi) {
    Engine2PINVOKE.IMeshFactory_DeleteMeshInfo(swigCPtr, IMeshInfo.getCPtr(mi));
  }

  public SWIGTYPE_p_ICullObject CreateObject(IMeshInfo mi) {
    global::System.IntPtr cPtr = Engine2PINVOKE.IMeshFactory_CreateObject(swigCPtr, IMeshInfo.getCPtr(mi));
    SWIGTYPE_p_ICullObject ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_ICullObject(cPtr, false);
    return ret;
  }

}
