//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MeshMergerInfo2 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MeshMergerInfo2(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MeshMergerInfo2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~MeshMergerInfo2() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_MeshMergerInfo2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public IMeshInfo m_pSourceMeshInfo {
    set {
      Engine2PINVOKE.MeshMergerInfo2_m_pSourceMeshInfo_set(swigCPtr, IMeshInfo.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Engine2PINVOKE.MeshMergerInfo2_m_pSourceMeshInfo_get(swigCPtr);
      IMeshInfo ret = (cPtr == global::System.IntPtr.Zero) ? null : new IMeshInfo(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_Engine2__VectorT_MeshMergerInstanceInfo_t m_Instances {
    set {
      Engine2PINVOKE.MeshMergerInfo2_m_Instances_set(swigCPtr, SWIGTYPE_p_Engine2__VectorT_MeshMergerInstanceInfo_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Engine2PINVOKE.MeshMergerInfo2_m_Instances_get(swigCPtr);
      SWIGTYPE_p_Engine2__VectorT_MeshMergerInstanceInfo_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Engine2__VectorT_MeshMergerInstanceInfo_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_Engine2__VectorT_IMeshInfo_p_t m_vResultMeshes {
    set {
      Engine2PINVOKE.MeshMergerInfo2_m_vResultMeshes_set(swigCPtr, SWIGTYPE_p_Engine2__VectorT_IMeshInfo_p_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Engine2PINVOKE.MeshMergerInfo2_m_vResultMeshes_get(swigCPtr);
      SWIGTYPE_p_Engine2__VectorT_IMeshInfo_p_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_Engine2__VectorT_IMeshInfo_p_t(cPtr, false);
      return ret;
    } 
  }

  public uint m_Flags2 {
    set {
      Engine2PINVOKE.MeshMergerInfo2_m_Flags2_set(swigCPtr, value);
    } 
    get {
      uint ret = Engine2PINVOKE.MeshMergerInfo2_m_Flags2_get(swigCPtr);
      return ret;
    } 
  }

  public MeshMergerInfo2() : this(Engine2PINVOKE.new_MeshMergerInfo2(), true) {
  }

}
