//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum eDebugMode {
  eNoDebugMode = 0,
  eBoxDebugMode = 1,
  eNormalsDebugMode = 2,
  eBoxAndBonesDebugMode = 3
}
