//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum EDeviceType {
  eDirectX9,
  eOpenGL_PC,
  eOpenGL_ES_PC,
  eOpenGL_ES_iOS,
  eOpenGL_ES_Android,
  eOpenGL_ES_Emscripten,
  eUnknownDevice
}
