//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum EDofParam {
  EDofP_BlurAmount,
  EDofP_FocusRange,
  EDofP_MaxCoC,
  EDofP_NearBlurDistance,
  EDofP_FarBlurDistance,
  EDofP_FocusDistance,
  EDofP_Num
}
