//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ERendererError {
  eRNE_OK,
  eRNE_Unknown,
  eRNE_D3DDeviceCreateFailed,
  eRNE_UnknownResolution,
  eRNE_UnsupportedShaderVersion,
  eRNE_HWFogNotSupported,
  eRNE_24BitDepthNotSupported,
  eRNE_32BitBufferNotSupported
}
