//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class example {
  public static ICore CreateCore(eStartGameType arg0, string pName) {
    global::System.IntPtr cPtr = examplePINVOKE.CreateCore__SWIG_0((int)arg0, pName);
    ICore ret = (cPtr == global::System.IntPtr.Zero) ? null : new ICore(cPtr, false);
    return ret;
  }

  public static ICore CreateCore(eStartGameType arg0) {
    global::System.IntPtr cPtr = examplePINVOKE.CreateCore__SWIG_1((int)arg0);
    ICore ret = (cPtr == global::System.IntPtr.Zero) ? null : new ICore(cPtr, false);
    return ret;
  }

  public static void DeleteCore(ICore pCore) {
    examplePINVOKE.DeleteCore(ICore.getCPtr(pCore));
  }

  public static int Color_RGBA(int r, int g, int b, int a, ERenderer rt) {
    int ret = examplePINVOKE.Color_RGBA(r, g, b, a, (int)rt);
    return ret;
  }

  public static int Color_RGBA_Texture(int r, int g, int b, int a, ERenderer rt) {
    int ret = examplePINVOKE.Color_RGBA_Texture(r, g, b, a, (int)rt);
    return ret;
  }

  public static readonly int ENGINE2_REV = examplePINVOKE.ENGINE2_REV_get();
  public static readonly int LogErrorMask = examplePINVOKE.LogErrorMask_get();
  public static readonly int LogNoCaretMask = examplePINVOKE.LogNoCaretMask_get();
  public static readonly int MM_USE_DIFFUSE_COLOR = examplePINVOKE.MM_USE_DIFFUSE_COLOR_get();
  public static readonly int FORCE_MATERIALS_AS_IDENTICAL = examplePINVOKE.FORCE_MATERIALS_AS_IDENTICAL_get();
  public static readonly int ALLOW_SUBMESHES_VISIBILITY = examplePINVOKE.ALLOW_SUBMESHES_VISIBILITY_get();
  public static readonly int CLEAR_COLLISION_INFO = examplePINVOKE.CLEAR_COLLISION_INFO_get();
  public static readonly int INSERT_INSTANCE_ID = examplePINVOKE.INSERT_INSTANCE_ID_get();
  public static readonly int BONE_INSTANCE_ID = examplePINVOKE.BONE_INSTANCE_ID_get();
}
