//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class I2DRenderObject : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public I2DRenderObject(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(I2DRenderObject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~I2DRenderObject() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_I2DRenderObject(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void SetMaterial(SWIGTYPE_p_IMaterial material) {
    Engine2PINVOKE.I2DRenderObject_SetMaterial(swigCPtr, SWIGTYPE_p_IMaterial.getCPtr(material));
  }

  public virtual void SetDefaultMaterial() {
    Engine2PINVOKE.I2DRenderObject_SetDefaultMaterial(swigCPtr);
  }

  public virtual void SetTexture(int num) {
    Engine2PINVOKE.I2DRenderObject_SetTexture(swigCPtr, num);
  }

  public virtual void SetBlendState(bool arg0) {
    Engine2PINVOKE.I2DRenderObject_SetBlendState(swigCPtr, arg0);
  }

  public virtual void SetBlendOperation(SWIGTYPE_p_eBLENDOP arg0) {
    Engine2PINVOKE.I2DRenderObject_SetBlendOperation(swigCPtr, SWIGTYPE_p_eBLENDOP.getCPtr(arg0));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetSrcBlend(SWIGTYPE_p_eBLEND arg0) {
    Engine2PINVOKE.I2DRenderObject_SetSrcBlend(swigCPtr, SWIGTYPE_p_eBLEND.getCPtr(arg0));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetDstBlend(SWIGTYPE_p_eBLEND arg0) {
    Engine2PINVOKE.I2DRenderObject_SetDstBlend(swigCPtr, SWIGTYPE_p_eBLEND.getCPtr(arg0));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetCullFunc(SWIGTYPE_p_eCULL arg0) {
    Engine2PINVOKE.I2DRenderObject_SetCullFunc(swigCPtr, SWIGTYPE_p_eCULL.getCPtr(arg0));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetDepthFunc(SWIGTYPE_p_eDEPTHSTATE arg0) {
    Engine2PINVOKE.I2DRenderObject_SetDepthFunc(swigCPtr, SWIGTYPE_p_eDEPTHSTATE.getCPtr(arg0));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetFillMode(int FM) {
    Engine2PINVOKE.I2DRenderObject_SetFillMode(swigCPtr, FM);
  }

  public virtual void SetAlphaFunc(SWIGTYPE_p_eCMPFUNC AF, int AV) {
    Engine2PINVOKE.I2DRenderObject_SetAlphaFunc__SWIG_0(swigCPtr, SWIGTYPE_p_eCMPFUNC.getCPtr(AF), AV);
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void SetAlphaFunc(SWIGTYPE_p_eCMPFUNC AF) {
    Engine2PINVOKE.I2DRenderObject_SetAlphaFunc__SWIG_1(swigCPtr, SWIGTYPE_p_eCMPFUNC.getCPtr(AF));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void DrawTriangle2DList(SWIGTYPE_p_RENDER2DVERTEX arg0, int triangleCount) {
    Engine2PINVOKE.I2DRenderObject_DrawTriangle2DList(swigCPtr, SWIGTYPE_p_RENDER2DVERTEX.getCPtr(arg0), triangleCount);
  }

  public virtual void DrawText(int font, float posx, float posy, int color, string text) {
    Engine2PINVOKE.I2DRenderObject_DrawText(swigCPtr, font, posx, posy, color, text);
  }

  public virtual void DrawTextScaled(int arg0, float arg1, float arg2, float arg3, float arg4, int arg5, string arg6) {
    Engine2PINVOKE.I2DRenderObject_DrawTextScaled(swigCPtr, arg0, arg1, arg2, arg3, arg4, arg5, arg6);
  }

  public virtual void BeginScene() {
    Engine2PINVOKE.I2DRenderObject_BeginScene(swigCPtr);
  }

  public virtual void EndScene() {
    Engine2PINVOKE.I2DRenderObject_EndScene(swigCPtr);
  }

}
