//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IChangesSubscription : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public IChangesSubscription(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(IChangesSubscription obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IChangesSubscription() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_IChangesSubscription(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual uint GetNumSubfolders() {
    uint ret = Engine2PINVOKE.IChangesSubscription_GetNumSubfolders(swigCPtr);
    return ret;
  }

  public virtual string GetSubfolder(uint arg0) {
    string ret = Engine2PINVOKE.IChangesSubscription_GetSubfolder(swigCPtr, arg0);
    return ret;
  }

  public virtual uint GetNumExtensions() {
    uint ret = Engine2PINVOKE.IChangesSubscription_GetNumExtensions(swigCPtr);
    return ret;
  }

  public virtual string GetExtension(uint arg0) {
    string ret = Engine2PINVOKE.IChangesSubscription_GetExtension(swigCPtr, arg0);
    return ret;
  }

  public virtual void FileChanged(string arg0) {
    Engine2PINVOKE.IChangesSubscription_FileChanged(swigCPtr, arg0);
  }

}
