//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IGUIRenderObject : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IGUIRenderObject(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IGUIRenderObject obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IGUIRenderObject() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_IGUIRenderObject(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void SetTexture(int num, int blend) {
    Engine2PINVOKE.IGUIRenderObject_SetTexture__SWIG_0(swigCPtr, num, blend);
  }

  public virtual void SetTexture(int num) {
    Engine2PINVOKE.IGUIRenderObject_SetTexture__SWIG_1(swigCPtr, num);
  }

  public virtual void SetEffect(int num, int Texture) {
    Engine2PINVOKE.IGUIRenderObject_SetEffect(swigCPtr, num, Texture);
  }

  public virtual void SetTextureNew(int num, int blend) {
    Engine2PINVOKE.IGUIRenderObject_SetTextureNew__SWIG_0(swigCPtr, num, blend);
  }

  public virtual void SetTextureNew(int num) {
    Engine2PINVOKE.IGUIRenderObject_SetTextureNew__SWIG_1(swigCPtr, num);
  }

  public virtual void SetLineMode() {
    Engine2PINVOKE.IGUIRenderObject_SetLineMode(swigCPtr);
  }

  public virtual void DrawTriangle2DList(SWIGTYPE_p_RENDER2DVERTEX arg0, int arg1, int nFlags) {
    Engine2PINVOKE.IGUIRenderObject_DrawTriangle2DList__SWIG_0(swigCPtr, SWIGTYPE_p_RENDER2DVERTEX.getCPtr(arg0), arg1, nFlags);
  }

  public virtual void DrawTriangle2DList(SWIGTYPE_p_RENDER2DVERTEX arg0, int arg1) {
    Engine2PINVOKE.IGUIRenderObject_DrawTriangle2DList__SWIG_1(swigCPtr, SWIGTYPE_p_RENDER2DVERTEX.getCPtr(arg0), arg1);
  }

  public virtual void DrawText(int font, float posx, float posy, int color, string text) {
    Engine2PINVOKE.IGUIRenderObject_DrawText(swigCPtr, font, posx, posy, color, text);
  }

  public virtual void DrawTextScaled(int arg0, float arg1, float arg2, float arg3, float arg4, int arg5, string arg6) {
    Engine2PINVOKE.IGUIRenderObject_DrawTextScaled(swigCPtr, arg0, arg1, arg2, arg3, arg4, arg5, arg6);
  }

}
