//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ILoadingProfilerManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public ILoadingProfilerManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(ILoadingProfilerManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ILoadingProfilerManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_ILoadingProfilerManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void EnableProfiling(bool b) {
    Engine2PINVOKE.ILoadingProfilerManager_EnableProfiling(swigCPtr, b);
  }

  public virtual void DumpStatsToXML(string arg0) {
    Engine2PINVOKE.ILoadingProfilerManager_DumpStatsToXML(swigCPtr, arg0);
  }

  public virtual Engine2String DumpStatsToString() {
    Engine2String ret = new Engine2String(Engine2PINVOKE.ILoadingProfilerManager_DumpStatsToString(swigCPtr), true);
    return ret;
  }

  public virtual int StartLoadingSection(string eventType, string evenName) {
    int ret = Engine2PINVOKE.ILoadingProfilerManager_StartLoadingSection(swigCPtr, eventType, evenName);
    return ret;
  }

  public virtual void EndLoadingSection(int arg0, double arg1) {
    Engine2PINVOKE.ILoadingProfilerManager_EndLoadingSection(swigCPtr, arg0, arg1);
  }

  public virtual int StartProfilerInfo(string section, string name) {
    int ret = Engine2PINVOKE.ILoadingProfilerManager_StartProfilerInfo(swigCPtr, section, name);
    return ret;
  }

  public virtual void EndProfilerInfo(int arg0, double arg1) {
    Engine2PINVOKE.ILoadingProfilerManager_EndProfilerInfo(swigCPtr, arg0, arg1);
  }

  public virtual void Clear() {
    Engine2PINVOKE.ILoadingProfilerManager_Clear(swigCPtr);
  }

}
