//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IMaterialInfo : IMeshInfo {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  public IMaterialInfo(global::System.IntPtr cPtr, bool cMemoryOwn) : base(Engine2PINVOKE.IMaterialInfo_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(IMaterialInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IMaterialInfo() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_IMaterialInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public virtual uint GetVisibleMaterialsCount() {
    uint ret = Engine2PINVOKE.IMaterialInfo_GetVisibleMaterialsCount(swigCPtr);
    return ret;
  }

  public virtual string GetVisibleMaterialName(uint arg0) {
    string ret = Engine2PINVOKE.IMaterialInfo_GetVisibleMaterialName(swigCPtr, arg0);
    return ret;
  }

  public virtual SWIGTYPE_p_IMaterial GetVisibleMaterial(uint num) {
    global::System.IntPtr cPtr = Engine2PINVOKE.IMaterialInfo_GetVisibleMaterial(swigCPtr, num);
    SWIGTYPE_p_IMaterial ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_IMaterial(cPtr, false);
    return ret;
  }

  public virtual bool SetVisibleMaterial(uint num, SWIGTYPE_p_IMaterial arg1) {
    bool ret = Engine2PINVOKE.IMaterialInfo_SetVisibleMaterial(swigCPtr, num, SWIGTYPE_p_IMaterial.getCPtr(arg1));
    return ret;
  }

  public virtual bool SetVisibleMaterialByMaterialName(uint mat, string newMat) {
    bool ret = Engine2PINVOKE.IMaterialInfo_SetVisibleMaterialByMaterialName(swigCPtr, mat, newMat);
    return ret;
  }

  public virtual uint GetVisibleMaterialParamCount(uint mat) {
    uint ret = Engine2PINVOKE.IMaterialInfo_GetVisibleMaterialParamCount(swigCPtr, mat);
    return ret;
  }

  public virtual SWIGTYPE_p_CParam GetVisibleMaterialParam(uint mat, uint param) {
    global::System.IntPtr cPtr = Engine2PINVOKE.IMaterialInfo_GetVisibleMaterialParam(swigCPtr, mat, param);
    SWIGTYPE_p_CParam ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_CParam(cPtr, false);
    return ret;
  }

  public virtual bool AddVisibleMaterialParam(uint mat, SWIGTYPE_p_CParam param) {
    bool ret = Engine2PINVOKE.IMaterialInfo_AddVisibleMaterialParam(swigCPtr, mat, SWIGTYPE_p_CParam.getCPtr(param));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool AddVisibleMaterialParamPtr(uint mat, SWIGTYPE_p_CParam param) {
    bool ret = Engine2PINVOKE.IMaterialInfo_AddVisibleMaterialParamPtr(swigCPtr, mat, SWIGTYPE_p_CParam.getCPtr(param));
    return ret;
  }

}
