//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IWindowListener : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public IWindowListener(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(IWindowListener obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IWindowListener() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_IWindowListener(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual void OnCreate() {
    Engine2PINVOKE.IWindowListener_OnCreate(swigCPtr);
  }

  public virtual void OnDestroy() {
    Engine2PINVOKE.IWindowListener_OnDestroy(swigCPtr);
  }

  public virtual void OnRequestClose() {
    Engine2PINVOKE.IWindowListener_OnRequestClose(swigCPtr);
  }

  public virtual void OnActivate() {
    Engine2PINVOKE.IWindowListener_OnActivate(swigCPtr);
  }

  public virtual void OnDeactivate() {
    Engine2PINVOKE.IWindowListener_OnDeactivate(swigCPtr);
  }

  public virtual void OnPreActivate() {
    Engine2PINVOKE.IWindowListener_OnPreActivate(swigCPtr);
  }

  public virtual void OnPreDeactivate() {
    Engine2PINVOKE.IWindowListener_OnPreDeactivate(swigCPtr);
  }

  public virtual void OnMove(int x, int y) {
    Engine2PINVOKE.IWindowListener_OnMove(swigCPtr, x, y);
  }

  public virtual void OnResize(int width, int height) {
    Engine2PINVOKE.IWindowListener_OnResize(swigCPtr, width, height);
  }

  public virtual void OnChangeStyle(uint arg0) {
    Engine2PINVOKE.IWindowListener_OnChangeStyle(swigCPtr, arg0);
  }

  public virtual void OnMemoryWarning() {
    Engine2PINVOKE.IWindowListener_OnMemoryWarning(swigCPtr);
  }

}
