//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IXmlParams : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IXmlParams(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IXmlParams obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IXmlParams() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_IXmlParams(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual CXmlParam GetParam(int arg0) {
    global::System.IntPtr cPtr = Engine2PINVOKE.IXmlParams_GetParam(swigCPtr, arg0);
    CXmlParam ret = (cPtr == global::System.IntPtr.Zero) ? null : new CXmlParam(cPtr, false);
    return ret;
  }

  public virtual int GetNumParams() {
    int ret = Engine2PINVOKE.IXmlParams_GetNumParams(swigCPtr);
    return ret;
  }

  public virtual CXmlParam GetParamByName(Engine2String szName) {
    global::System.IntPtr cPtr = Engine2PINVOKE.IXmlParams_GetParamByName(swigCPtr, Engine2String.getCPtr(szName));
    CXmlParam ret = (cPtr == global::System.IntPtr.Zero) ? null : new CXmlParam(cPtr, false);
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual string GetValueByName(Engine2String arg0) {
    string ret = Engine2PINVOKE.IXmlParams_GetValueByName(swigCPtr, Engine2String.getCPtr(arg0));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void SetParam(Engine2String arg0, Engine2String arg1) {
    Engine2PINVOKE.IXmlParams_SetParam(swigCPtr, Engine2String.getCPtr(arg0), Engine2String.getCPtr(arg1));
    if (Engine2PINVOKE.SWIGPendingException.Pending) throw Engine2PINVOKE.SWIGPendingException.Retrieve();
  }

}
