//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class LightmapInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public LightmapInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(LightmapInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LightmapInfo() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_LightmapInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public CVec2 m_vecLightmapWorldCoord {
    set {
      Engine2PINVOKE.LightmapInfo_m_vecLightmapWorldCoord_set(swigCPtr, CVec2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Engine2PINVOKE.LightmapInfo_m_vecLightmapWorldCoord_get(swigCPtr);
      CVec2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new CVec2(cPtr, false);
      return ret;
    } 
  }

  public CVec2 m_vecLightmapSizeInWorld {
    set {
      Engine2PINVOKE.LightmapInfo_m_vecLightmapSizeInWorld_set(swigCPtr, CVec2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Engine2PINVOKE.LightmapInfo_m_vecLightmapSizeInWorld_get(swigCPtr);
      CVec2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new CVec2(cPtr, false);
      return ret;
    } 
  }

  public LightmapInfo() : this(Engine2PINVOKE.new_LightmapInfo(), true) {
  }

}
