//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SAAFormat : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public SAAFormat(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(SAAFormat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SAAFormat() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_SAAFormat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string szDescr {
    set {
      Engine2PINVOKE.SAAFormat_szDescr_set(swigCPtr, value);
    } 
    get {
      string ret = Engine2PINVOKE.SAAFormat_szDescr_get(swigCPtr);
      return ret;
    } 
  }

  public int nSamples {
    set {
      Engine2PINVOKE.SAAFormat_nSamples_set(swigCPtr, value);
    } 
    get {
      int ret = Engine2PINVOKE.SAAFormat_nSamples_get(swigCPtr);
      return ret;
    } 
  }

  public int nQuality {
    set {
      Engine2PINVOKE.SAAFormat_nQuality_set(swigCPtr, value);
    } 
    get {
      int ret = Engine2PINVOKE.SAAFormat_nQuality_get(swigCPtr);
      return ret;
    } 
  }

  public int nAPIType {
    set {
      Engine2PINVOKE.SAAFormat_nAPIType_set(swigCPtr, value);
    } 
    get {
      int ret = Engine2PINVOKE.SAAFormat_nAPIType_get(swigCPtr);
      return ret;
    } 
  }

  public SAAFormat() : this(Engine2PINVOKE.new_SAAFormat(), true) {
  }

}
