//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SDispFormat : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public SDispFormat(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(SDispFormat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SDispFormat() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_SDispFormat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public int m_Width {
    set {
      Engine2PINVOKE.SDispFormat_m_Width_set(swigCPtr, value);
    } 
    get {
      int ret = Engine2PINVOKE.SDispFormat_m_Width_get(swigCPtr);
      return ret;
    } 
  }

  public int m_Height {
    set {
      Engine2PINVOKE.SDispFormat_m_Height_set(swigCPtr, value);
    } 
    get {
      int ret = Engine2PINVOKE.SDispFormat_m_Height_get(swigCPtr);
      return ret;
    } 
  }

  public int m_BPP {
    set {
      Engine2PINVOKE.SDispFormat_m_BPP_set(swigCPtr, value);
    } 
    get {
      int ret = Engine2PINVOKE.SDispFormat_m_BPP_get(swigCPtr);
      return ret;
    } 
  }

  public SDispFormat() : this(Engine2PINVOKE.new_SDispFormat(), true) {
  }

}
