//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SFontStatistics : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SFontStatistics(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SFontStatistics obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SFontStatistics() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_SFontStatistics(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public uint m_atlasHeight {
    set {
      Engine2PINVOKE.SFontStatistics_m_atlasHeight_set(swigCPtr, value);
    } 
    get {
      uint ret = Engine2PINVOKE.SFontStatistics_m_atlasHeight_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_atlasWidth {
    set {
      Engine2PINVOKE.SFontStatistics_m_atlasWidth_set(swigCPtr, value);
    } 
    get {
      uint ret = Engine2PINVOKE.SFontStatistics_m_atlasWidth_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_textureCount {
    set {
      Engine2PINVOKE.SFontStatistics_m_textureCount_set(swigCPtr, value);
    } 
    get {
      uint ret = Engine2PINVOKE.SFontStatistics_m_textureCount_get(swigCPtr);
      return ret;
    } 
  }

  public uint m_generationTimeMs {
    set {
      Engine2PINVOKE.SFontStatistics_m_generationTimeMs_set(swigCPtr, value);
    } 
    get {
      uint ret = Engine2PINVOKE.SFontStatistics_m_generationTimeMs_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int m_textures {
    set {
      Engine2PINVOKE.SFontStatistics_m_textures_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Engine2PINVOKE.SFontStatistics_m_textures_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public SFontStatistics() : this(Engine2PINVOKE.new_SFontStatistics(), true) {
  }

}
