//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.7
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class UVAnimationParam : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  public UVAnimationParam(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  public static global::System.Runtime.InteropServices.HandleRef getCPtr(UVAnimationParam obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~UVAnimationParam() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Engine2PINVOKE.delete_UVAnimationParam(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public UVAnimationParam() : this(Engine2PINVOKE.new_UVAnimationParam(), true) {
  }

  public float m_fSpeed {
    set {
      Engine2PINVOKE.UVAnimationParam_m_fSpeed_set(swigCPtr, value);
    } 
    get {
      float ret = Engine2PINVOKE.UVAnimationParam_m_fSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public bool m_bGameUpdate {
    set {
      Engine2PINVOKE.UVAnimationParam_m_bGameUpdate_set(swigCPtr, value);
    } 
    get {
      bool ret = Engine2PINVOKE.UVAnimationParam_m_bGameUpdate_get(swigCPtr);
      return ret;
    } 
  }

  public bool m_bLooped {
    set {
      Engine2PINVOKE.UVAnimationParam_m_bLooped_set(swigCPtr, value);
    } 
    get {
      bool ret = Engine2PINVOKE.UVAnimationParam_m_bLooped_get(swigCPtr);
      return ret;
    } 
  }

}
